language: java
jdk:
  - oraclejdk7
  - openjdk7

services:
  - mysql

service_name: 
  - travis-pro

before_script:
  - mysql -e 'CREATE DATABASE test;'
  - mysql test < hblog.sql
  
script: 
  - mvn test -f pom.xml

after_script:
  - mysql -e 'DROP DATABASE test;'

after_success:
  - mvn clean cobertura:cobertura coveralls:report
